[2021-08-31 13:27:50,004] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: snowflake_test.snowfalke_create 2021-08-31T12:47:01.760509+00:00 [queued]>
[2021-08-31 13:27:50,071] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: snowflake_test.snowfalke_create 2021-08-31T12:47:01.760509+00:00 [queued]>
[2021-08-31 13:27:50,076] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-08-31 13:27:50,100] {taskinstance.py:1095} INFO - Starting attempt 8 of 8
[2021-08-31 13:27:50,101] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-08-31 13:27:50,114] {taskinstance.py:1114} INFO - Executing <Task(SnowflakeOperator): snowfalke_create> on 2021-08-31T12:47:01.760509+00:00
[2021-08-31 13:27:50,124] {standard_task_runner.py:52} INFO - Started process 765 to run task
[2021-08-31 13:27:50,130] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'snowflake_test', 'snowfalke_create', '2021-08-31T12:47:01.760509+00:00', '--job-id', '44', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/snowflake.py', '--cfg-path', '/tmp/tmpqb516l3n', '--error-file', '/tmp/tmpepnovgcj']
[2021-08-31 13:27:50,196] {standard_task_runner.py:77} INFO - Job 44: Subtask snowfalke_create
[2021-08-31 13:27:50,241] {logging_mixin.py:109} INFO - Running <TaskInstance: snowflake_test.snowfalke_create 2021-08-31T12:47:01.760509+00:00 [running]> on host f134af24bd93
[2021-08-31 13:27:50,326] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=snowflake_test
AIRFLOW_CTX_TASK_ID=snowfalke_create
AIRFLOW_CTX_EXECUTION_DATE=2021-08-31T12:47:01.760509+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-31T12:47:01.760509+00:00
[2021-08-31 13:27:50,331] {snowflake.py:121} INFO - Executing: insert into TEST_TABLE values('', '')
[2021-08-31 13:27:50,360] {base.py:70} INFO - Using connection to: id: snowflake_default. Host: https://tm52136.west-us-2.azure.snowflakecomputing.com/, Port: None, Schema: RPY_SCH, Login: incspn, Password: ***, extra: {'extra__snowflake__account': 'tm52136', 'extra__snowflake__aws_access_key_id': '', 'extra__snowflake__aws_secret_access_key': '***', 'extra__snowflake__database': 'RPY_DB', 'extra__snowflake__region': 'west-us-2.azure', 'extra__snowflake__role': '', 'extra__snowflake__warehouse': ''}
[2021-08-31 13:27:50,365] {connection.py:270} INFO - Snowflake Connector for Python Version: 2.6.0, Python Version: 3.8.11, Platform: Linux-5.4.0-81-generic-x86_64-with-glibc2.2.5
[2021-08-31 13:27:50,371] {connection.py:890} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2021-08-31 13:27:50,381] {connection.py:908} INFO - Setting use_openssl_only mode to False
[2021-08-31 13:27:51,752] {base.py:70} INFO - Using connection to: id: snowflake_default. Host: https://tm52136.west-us-2.azure.snowflakecomputing.com/, Port: None, Schema: RPY_SCH, Login: incspn, Password: ***, extra: {'extra__snowflake__account': 'tm52136', 'extra__snowflake__aws_access_key_id': '', 'extra__snowflake__aws_secret_access_key': '***', 'extra__snowflake__database': 'RPY_DB', 'extra__snowflake__region': 'west-us-2.azure', 'extra__snowflake__role': '', 'extra__snowflake__warehouse': ''}
[2021-08-31 13:27:51,768] {connection.py:270} INFO - Snowflake Connector for Python Version: 2.6.0, Python Version: 3.8.11, Platform: Linux-5.4.0-81-generic-x86_64-with-glibc2.2.5
[2021-08-31 13:27:51,776] {connection.py:890} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2021-08-31 13:27:52,320] {cursor.py:678} INFO - query: [ALTER SESSION SET autocommit=True]
[2021-08-31 13:27:52,443] {cursor.py:702} INFO - query execution done
[2021-08-31 13:27:52,458] {snowflake.py:284} INFO - Running statement: insert into TEST_TABLE values('', ''), parameters: None
[2021-08-31 13:27:52,476] {cursor.py:678} INFO - query: [insert into TEST_TABLE values('', '')]
[2021-08-31 13:27:53,142] {cursor.py:702} INFO - query execution done
[2021-08-31 13:27:53,152] {snowflake.py:292} INFO - Statement execution info - {'number of rows inserted': 1}
[2021-08-31 13:27:53,179] {snowflake.py:295} INFO - Rows affected: 1
[2021-08-31 13:27:53,193] {snowflake.py:296} INFO - Snowflake query id: 019ea2e7-0000-6d3a-0000-00008bd12199
[2021-08-31 13:27:53,194] {connection.py:521} INFO - closed
[2021-08-31 13:27:53,208] {connection.py:524} INFO - No async queries seem to be running, deleting session
[2021-08-31 13:27:53,354] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=snowflake_test, task_id=snowfalke_create, execution_date=20210831T124701, start_date=20210831T132750, end_date=20210831T132753
[2021-08-31 13:27:53,429] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-08-31 13:27:53,493] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
